service: prueba-python

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-2
  iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "secretsmanager:*"
    Resource: "*"



functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: post

plugins:
  - serverless-wsgi
  - serverless-python-requirements